Repository prgrms-aibe-devcourse/AIBE3_Project1_Team5, pull requests merged in 2025-07, with the labels that each got.

#9 Enhancement/8
  app/components/Navigation.tsx
  app/components/SocialLogin.tsx
  app/login/page.tsx
  app/providers/AuthProvider.tsx
  app/setprofile/page.tsx
  app/signup/page.tsx
  package-lock.json
  package.json
Labels: enhancement, fix

#15 Refactor/10
  app/components/inputForm/ConfirmPasswordInput.tsx
  app/components/inputForm/EmailInput.tsx
  app/components/inputForm/NicknameInput.tsx
  app/components/inputForm/PasswordInput.tsx
  app/login/page.tsx
  app/providers/AuthProvider.tsx
  app/setprofile/page.tsx
  app/signup/page.tsx
  hooks/useInputValidator.ts
  lib/authValidator.ts
Labels: enhancement, refactor

#21 Profile의 id 제거 및 user_id를 User의 id(PK)로 변경, 불필요한 import 제거
  app/login/page.tsx
  app/providers/AuthProvider.tsx
  app/setprofile/page.tsx
  app/signup/page.tsx
  lib/authValidator.ts
Labels: enhancement, refactor

#26 [Feat]카카오 소셜 로그인 추가
  app/components/SocialLogin.tsx
  app/providers/AuthProvider.tsx
  public/pngegg.png
Labels: enhancement

#32 후기 검색 기능 추가 + etc
  app/reviews/page.tsx
Labels: enhancement

#34 review 기능 컴포넌트 분리
  app/reviews/page.tsx
  components/reviews/ReviewCard.tsx
  components/reviews/ReviewForm.tsx
  components/reviews/ReviewList.tsx
  components/reviews/ReviewSearchBar.tsx
Labels: refactor

#38 후기 페이지네이션 적용
  app/reviews/page.tsx
  components/reviews/ReviewCard.tsx
Labels: enhancement

#45 페이지네이션 기능 수정 및 json 파일 변화
  app/reviews/page.tsx
  package-lock.json
Labels: enhancement, fix

#47 [Chore] 로그인 실패시 에러 메시지 개선
  app/login/page.tsx
Labels: enhancement
